on: [push, pull_request, workflow_call, workflow_dispatch]

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-20.04
    steps:
    - name: Skeleton Builder
      # You may pin to the exact commit or the version.
      # uses: getgrav/skeleton-builder@3ae94b5a55d670e7f44e525a34d4f5afa5d8f5e6
      uses: getgrav/skeleton-builder@v1.0.1
      with:
        version: latest
        admin: true
        filename_version: true
        verbose: true
